--- 
kafka: 
  bootstrap-servers: "localhost:9092"
  consumergroup: requestreplygroup
  topic: 
    request-topic: request-topic
    request-topic-parition-id: parition-id-1
    requestreply-topic: requestreply-topic
server: 
  port: 8080
spring: 
  application: 
    name: request_reply_kafka
